### ISSUE TITLE
Problemas en el proyecto

### ISSUE THREAD

**Issue by dagoull** [angelcapote/AirportLDH#1]
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.manning.junitbook:ch13-continuous:jar:1.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: junit:junit:jar -> duplicate declaration of version 3.8.2 @ line 48, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]

**Comment by angelcapote** [comment]
Había puesto dos veces la misma dependencia, ya lo he corregido en la nueva versión, Gracias!
